# https://docs.docker.com/compose/compose-file/
version: '3.7'
networks:
  app-tier:
    driver: bridge

services:
# caocaocao/tracker
  tracker:
    image: 'caocaocao/web:latest'
    container_name: 'news_tb_dev'
    user: root
    working_dir: "/app/"
    ports:
      - 12345:9999
    volumes:
      - .:/app/tb_news
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - WEB_BRANCH=master
      - WEB_PRODORDEV=dev
      - HOST=0.0.0.0
      - WEB_PROJECT_NAME=tb_news
      - WEB_GIT_ADDR=https://github.com/caozijian2018/tb_news.git
      - WEB_NEED_NPM_REGISTRY=true
      - IS_DOCKER=true
      - WEB_COMMITID=f5f0ee336558d6cd52f519c05250af8ce0d30527
    command: 
        - /bin/sh
        - -c
        - |
          cd tb_news
          sh deploy_auto.sh
          tail -f /dev/null